DEBUG = True
SECRET_KEY = b'jsm@9d0)/.skl'

_MYSQL_USERNAME = 'root'
_MYSQL_PASSWORD = 'ZQSzqs121402!'
_MYSQL_HOST = '127.0.0.1:3306'
_MYSQL_DBNAME = 'Vision'
SQLALCHEMY_DATABASE_URI = 'mysql://{}:{}@{}/{}'.format(_MYSQL_USERNAME, _MYSQL_PASSWORD, _MYSQL_HOST, _MYSQL_DBNAME)